language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64_unknown_linux_gnu
    - os: linux
      rust: nightly
      env: TARGET=x86_64_unknown_linux_gnu

